version: '3.8'

services:
  # Serveur PHP pour le backend Symfony
  backend:
    build: docker/web
    container_name: todo_backend
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://todo_user:todo_password@db:3306/todo_app"
      OAUTH_ENCRYPTION_KEY: abcd
      SERVERNAME: api.labelleadresse.local
      SERVERALIAS: api.labelleadresse.local
      DOCUMENTROOT: docroot/public
      PHP_IDE_CONFIG: "serverName=api.labelleadresse.local"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_SESSION: "PHPSTORM"
      APP_SECRET: 123456
    depends_on:
      - db

  # Serveur Node pour le frontend
  frontend:
    image: node:16-alpine
    container_name: todo_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm start

  # Base de données MySQL
  db:
    image: mysql:8.0
    container_name: todo_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: